### ISSUE TITLE
 java.lang.NoClassDefFoundError: com.firebase.client.Firebase

### ISSUE THREAD

**Issue by datomnurdin** [firebase/AndroidChat#18] opened 2015-03-11 17:20 UTC
I just run you app then suddenly crash. I just found out that your android SDK don't have ```com.firebase.client.Firebase``` class

Error message

```
03-12 01:19:31.664: E/AndroidRuntime(29209): java.lang.NoClassDefFoundError: com.firebase.client.Firebase
```

**Comment by nandha-dev** [comment] 2015-05-27 15:31
Add Firebase SDK to the project.

**Comment by ShreyashPromact** [comment] 2015-06-26 14:45
@nandha-dev  @datomnurdin 
I have added thedepandency as mention in quick start. But it seems like not working. I am still getting crashing problem.

I have also remove the dependency and add jar library. But still no solution. 
I really need help in that to start working my app.

Sincerely,
Shreyash

**Comment by ShreyashPromact** [comment] 2015-06-26 14:48
Hello, @datomnurdin @nandha-dev 

I have follow the instruction to integrate Firebase as explain below:
	https://www.firebase.com/docs/android/quickstart.html

	However, it is working fine with Lollipop devices. But when I run same app in android devices lower then Lollipop, the application get crashed. I have checked the log, which shows the error like below:

	java.lang.VerifyError: com/firebase/client/Firebase

I have check the log and come to know that, the issue is at below line:

	Firebase.setAndroidContext(this);

I have Google about this issue, somewhere found one suggestion that you need to add jar file. So I have remove dependency and added jar file as mention. But even after adding jar library, I am not getting success in it. I am not figure out where it the issue.

I need your reply in solution to this.

Thanks.

**Comment by ShreyashPromact** [comment] 2015-06-30 06:21
Hello, @datomnurdin @nandha-dev 

I have try in so many ways but could not able to resolved this issue. Its very strange issue. I have just mane new TestApp and integrate Firebase in it. Its working fine, but when i run my original app, it get crashed. 

Need someone expert to help in this.

FYI, Error log is like as below.....

 java.lang.VerifyError: com/firebase/client/Firebase
            at com.somename.myappname.MyApplication.onCreate(MyApplication.java:37)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
            at android.app.ActivityThread.access$1300(ActivityThread.java:130)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)



Sincerely,
Shreyash

**Comment by puf** [comment] 2015-06-30 16:43
Hi Shreyash,

I've just pulled a clean copy of the AndroidChat repo and don't see any problems when I run it. Can you post a minimal reproduction of your problem, e.g. by creating a repo with your project?

       Frank

**Comment by ShreyashPromact** [comment] 2015-07-01 06:41
@puf @datomnurdin 

Hello, I am not sure, where is the exact issue. But it is resolved when i have updated the google plat service library.

Initially i don't know the version of the google play library. So i have added it like below:
compile 'com.google.android.gms:play-services:4.+'  

( I have added like this because somewhere it is written that, with this it will automatically detect the version of the google play store.)
However i am not getting compilation error or any other problem but it get crashed on the Lower version of android devices on mention line of  Firebase.

I have manually, remove login one by one and then add it and when i change the play service library, it seems like proper working. I have added below library version of the google plays service

compile 'com.google.android.gms:play-services:4.1.0'

It is really strange issue. Firebase should work with any google play library version but it is not for android lower version.

Anyway, thanks for the reply and support for the issue. I would like you to check in the google play services library and check whether there is issue with that or not.

Thanks.

Sincerely,
Shreyash

**Comment by ShreyashPromact** [comment] 2015-07-01 13:23
@puf @datomnurdin 

Once the issue is resolved as i have explained above. But after that i got another issue of VarifyError on another screen of my app.

I have search a lot for the cause of that issue. Please refer below link for same:
http://stackoverflow.com/questions/100107/reasons-of-getting-a-java-lang-verifyerror
http://stackoverflow.com/questions/668788/android-java-lang-verifyerror
http://solvedstack.com/questions/reasons-of-getting-a-java-lang-verifyerror
http://solvedstack.com/questions/android-java-lang-verifyerror

Finally I have removed the firebace library and code from my project and do try. Problem is resolved.

Still i am not sure why this issue happen, but that is sure that if I remove firebase, application works fine without VarifyError but if i add Firebase library, I got VarifyError on unexpected screen.

I guess, there might be some class file in firebase library causes the VarifyError issue.
I will wait to have solution to this issue.

FYI, Do not try the demo given by firebase, but add that dependency to own project and try it. I have Facebook library, Fabric library and google play library available in my project.

Sincerely,
Shreyash

**Comment by puf** [comment] 2015-07-01 15:06
This thread is already quite long and I still have not reproduced your problem. Can you post a repo that reproduces the problem you are having?

**Comment by ShreyashPromact** [comment] 2015-07-02 03:49
@puf 
Well, I can not upload code on github as its a privacy policy of the client I am working with. I can make a demo and will share it with you. Give me some time, i will do it and let you know.

Thanks for the reply and support.

Sincerely,
Shreyash

**Comment by katowulf** [comment] 2015-07-02 04:36
Thanks, @ShreyashPromact! A demo is usually much better than a copy of the code anyway. We generally don't have the experience and bandwidth to troubleshoot an entire app, but by simplifying it to a smaller sample (presumably something that will be fairly straightforward if you understand the code and the use case), it makes the problem much easier to spot and address.

**Comment by puf** [comment] 2015-07-02 15:54
@ShreyashPromact am I correct that the issue is not strictly based on this AndroidChat repo? In that case it might also be better to move it over to a more generic place like StackOverflow. Both Kato and I will be there too, but you'll also get a much wider audience.

**Comment by ShreyashPromact** [comment] 2015-07-03 04:54
@puf 
Yes true. Please share a link of stackoverflow with me. I will be available there to discuss regarding this things. If there is no other issue in this, you can please close this issue.

Thanks.

Sincerely,
Shreyash

**Comment by puf** [comment] 2015-07-03 15:12
www.stackoverflow.com Tag your question with Firebase and Android. See this link for their description of a minimal reproduction: http://stackoverflow.com/help/mcve

**Closed by puf** 2015-07-03 15:12 UTC
