### ISSUE TITLE
Immidiatly Disconnects

### ISSUE THREAD

**Issue by samdarcy42** [firebase/AndroidChat#19] opened 2015-04-23 12:42 UTC
I have downloaded the code and changed the firebase reference, however, on launch I immediately receive the disconnected toast. I am online and have made the appropriate permissions in my Manifest. Any help would be appreciated!

**Comment by nandha-dev** [comment] 2015-05-27 15:26
It is now fixed. It was because of the not well formed JSON data.

**Comment by iamgyz** [comment] 2015-06-04 19:11
Hello samdarcy42:
You can check that if you can directly access Firebase in your device (or emulator).
Maybe there is a proxy issue in your environment.
Just a little suggestion, hope it is helpful :)

**Comment by puf** [comment] 2015-06-04 19:17
Hi samdarcy. I get the initial "Disconnected" toast too. But after that the app connects. So it just looks weird, but works fine. Does the app connect in your case? If not, iamgyz' suggestion might indeed help troubleshooting.

**Comment by iamgyz** [comment] 2015-06-07 18:04
Hello samdarcy42:
Any new progress about this?

**Comment by sanjaydevhack** [comment] 2015-07-10 10:19
I am also facing the same problem, and the app crashes immediately.   

Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "to" (class com.firebase.androidchat.Chat), not marked as ignorable (2 known properties: , "author", "message"])

**Comment by puf** [comment] 2015-07-10 16:51
That problem would normally be caused by a faulty JSON in the database. But when I just ran the app on me Nexus 7 against https://android-chat.firebaseio-demo.com/ it renders everything fine. Are you running against a different URL? If so, you'll want to check your data there.

**Closed by puf** 2015-07-10 16:51 UTC
